#!/bin/bash
#
## Run all phenotype notebooks
#
# ARG_OPTIONAL_SINGLE([rds],[u],[MHQ2 fields RDS file])
# ARG_HELP([Run all phenotype notebooks.])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.9.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info
# Generated online by https://argbash.io/generate


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='uh'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_rds=


print_help()
{
	printf '%s\n' "Run all phenotype notebooks."
	printf 'Usage: %s [-u|--rds <arg>] [-h|--help]\n' "$0"
	printf '\t%s\n' "-u, --rds: MHQ2 fields RDS file (no default)"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-u|--rds)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_rds="$2"
				shift
				;;
			--rds=*)
				_arg_rds="${_key##--rds=}"
				;;
			-u*)
				_arg_rds="${_key##-u}"
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
				;;
		esac
		shift
	done
}

parse_commandline "$@"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash


mkdir -p reports
mkdir -p outputs

for rmd in scripts/*.Rmd; do
    rds=$(readlink -f $_arg_rds)
    html_document="$(basename $_arg_rds .rds)-$(basename $rmd .Rmd).html"
    output="$(basename $_arg_rds .rds)-$(basename $rmd .Rmd).tsv"
    Rscript -e "rmarkdown::render('${rmd}', params = list(fields = '$rds', output = '$output'), output_file = '${html_document}')"
    mv scripts/${html_document} reports/
    mv scripts/${output} outputs/
done

# ] <-- needed because of Argbash
